### ISSUE TITLE
Add item description to inventory menu

### ISSUE THREAD

**Issue by sandstrand** [Legofarmen/tunics#7]
It is not always clear how a dungeon item should be used. 

There is a description which can be accessed by pressing the action button while an item is highlighted but it would be better to have a text field always visible to display the description of the highlighted item.
- Add description field to inventory menu.
- Review and update item descriptions.

**Comment by sandstrand** [comment]
New png at https://github.com/sandstrand/tunics/tree/add-item-description-to-inventory-menu.
The image allows for three rows of text with the same linespacing as a dialog box.

**Comment by mattias-p** [comment]
So the discoverability of item descriptions is improved by always showing the description of the selected item, instead of showing a popup dialog as a response to the action button.

To get to know the passive items the player must have the ability to move cursor through the those items as well. The description of a passive items must convey its passive nature so that the equip buttons can be silently ignored for those items. To indicate that passive items can't be equipped, the opacity of the cursor is lowered in the passive items area.
